/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-10-10 06:03:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.missing;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modifymissing_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/lecture/final/dodam/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dodam/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1631675128238L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>	\r\n");
      out.write("	let uploadImgAr = [];\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#no\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"#title\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"#writer\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"#animal\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.animal }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"#breed\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.breed }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"#gender\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.gender }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"#name\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"#age\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.age }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"#location\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.location }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"#dlocation\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.dlocation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"#missingdate\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.missingdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".split(\" \")[0]);\r\n");
      out.write("		$(\"#contact\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.contact }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		let output = '';\r\n");
      out.write("		if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.dpchknum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"\") {\r\n");
      out.write("			let thumbAr = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.thumbimg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".split(\", \");\r\n");
      out.write("			console.log(thumbAr);\r\n");
      out.write("			\r\n");
      out.write("			for(let i in thumbAr) {\r\n");
      out.write("				if (thumbAr[i] != '') {\r\n");
      out.write("					i = parseInt(i);\r\n");
      out.write("					$(\".fileContent\").show();\r\n");
      out.write("					console.log(i+1);\r\n");
      out.write("					output += '<span id=\"imgPreview' + (i+1) + '\" style=\"margin-right: 50px;\"><img src=\"../resources/uploads' + thumbAr[i] + '\" style=\"margin-right: 5px;\" />' +\r\n");
      out.write("						'<img src=\"../resources/images/missing/cancel.png\" style=\"width: 20px;\" onclick=\"delImg(this);\" /></span>';\r\n");
      out.write("						\r\n");
      out.write("					// 썸네일과 원래이미지를 input hidden에 저장\r\n");
      out.write("					$(\"#upImgNameThumb\" + (i+1)).val(thumbAr[i]);\r\n");
      out.write("					let splitName = thumbAr[i].split(\"thumb_\");\r\n");
      out.write("					let origin = splitName[0] + splitName[1];\r\n");
      out.write("					\r\n");
      out.write("					$(\"#upImgNameOrigin\" + (i+1)).val(origin);\r\n");
      out.write("\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		} else {\r\n");
      out.write("			let imgAr = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".split(\", \");\r\n");
      out.write("			console.log(imgAr);\r\n");
      out.write("			for (let i in imgAr) {\r\n");
      out.write("				i = parseInt(i);\r\n");
      out.write("				if (imgAr[i] != '') {\r\n");
      out.write("					$(\".fileContent\").show();\r\n");
      out.write("					output += '<span id=\"imgPreview' + (i+1) + '\" style=\"margin-right: 50px;\"><img src=\"' + imgAr[i] + '\" style=\"margin-right: 5px;\" />' +\r\n");
      out.write("					'<img src=\"../resources/images/missing/cancel.png\" style=\"width: 20px;\" onclick=\"delUrlImg(this);\" /></span>';\r\n");
      out.write("					\r\n");
      out.write("					$(\"#upImgNameOrigin\" + (i+1)).val(imgAr[i]);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		// 미리보기 div에 썸네일 사진 띄우기\r\n");
      out.write("		$(\".fDropList\").html(output);\r\n");
      out.write("		\r\n");
      out.write("		$(\".fileDrop\").on(\"dropenter dragover\", function(e) {\r\n");
      out.write("			e.preventDefault();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\".fileDrop\").on(\"drop\", function(e) {\r\n");
      out.write("			e.preventDefault(); // drop된 파일이 chrome브라우저에서 열리는 이벤트 전파를 막음\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			// ### 고칠점 : 새로 드래그 앤 드롭하면 원래 업로드 된 파일을 삭제하고 새로 업로드 해야함!! ###\r\n");
      out.write("			// insert구현하기\r\n");
      out.write("			$(\"#uploadError\").empty();			\r\n");
      out.write("			let files = e.originalEvent.dataTransfer.files; // 드래그 된 파일을 얻어옴\r\n");
      out.write("			console.log(files);\r\n");
      out.write("			for(let i in files) {\r\n");
      out.write("				uploadImgAr[i] = files[i];\r\n");
      out.write("			}\r\n");
      out.write("			console.log(uploadImgAr);\r\n");
      out.write("			\r\n");
      out.write("			if (uploadImgAr.length > 3) {\r\n");
      out.write("				$(\"#uploadError\").append(\"사진은 3개까지만 업로드 가능합니다!\");\r\n");
      out.write("			} else if (notImgCheck(uploadImgAr)) {\r\n");
      out.write("				$(\"#uploadError\").append(\"이미지 파일만 업로드 가능합니다!\");\r\n");
      out.write("			} else {\r\n");
      out.write("				// 게시글 등록 전 이미지 파일 먼저 업로드\r\n");
      out.write("				let formData = new FormData(); // form 객체 생성\r\n");
      out.write("				for(let i = 0; i < uploadImgAr.length; i++) { // form 객체에 파일 첨부\r\n");
      out.write("					formData.append(\"uploadImg\", uploadImgAr[i]);\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				let url = '/missing/uploadImgs';\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : url, // ajax와 통신 할 곳\r\n");
      out.write("					data : formData, // 서블릿에 보낼 데이터\r\n");
      out.write("					dataType : \"text\", // 수신될 데이터의 타입\r\n");
      out.write("					type : \"post\", // 통신 방식\r\n");
      out.write("					processData : false, // 전송하는 데이터를 쿼리 스트링 형태로 반환하는지를 결정(파일은 길이가 길기 때문에 url길이 초과됨)\r\n");
      out.write("					contentType : false, // encType의 기본값 (application/x-www-form-urlencoded) multipart/form-data 쓸거니까 false\r\n");
      out.write("					success : function(data) { // 통신 성공시 수행될 콜백 함수\r\n");
      out.write("						let thumbImgs = data.split(\", \");\r\n");
      out.write("						console.log(thumbImgs);\r\n");
      out.write("						let output = \"\";\r\n");
      out.write("						for(let i = 0; i < thumbImgs.length-1; i++) {\r\n");
      out.write("							output += '<span id=\"imgPreview' + (i+1) + '\" style=\"margin-right: 50px;\"><img src=\"../resources/uploads' + thumbImgs[i] + '\" style=\"margin-right: 5px;\" />' +\r\n");
      out.write("							'<img src=\"../resources/images/missing/cancel.png\" style=\"width: 20px;\" onclick=\"delImg(this);\" /></span>';\r\n");
      out.write("							\r\n");
      out.write("							// 썸네일과 원래이미지를 input hidden에 저장\r\n");
      out.write("							$(\"#upImgNameThumb\" + (i+1)).val(thumbImgs[i]);\r\n");
      out.write("							let splitName = thumbImgs[i].split(\"thumb_\");\r\n");
      out.write("							let origin = splitName[0] + splitName[1];\r\n");
      out.write("							\r\n");
      out.write("							$(\"#upImgNameOrigin\" + (i+1)).val(origin);\r\n");
      out.write("							\r\n");
      out.write("							// 미리보기 div에 썸네일 사진 띄우기\r\n");
      out.write("							$(\".fDropList\").html(output);\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				});	\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#cancelBtn\").click(function() {\r\n");
      out.write("			location.href='/missing/detail?no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function delImg(obj) {\r\n");
      out.write("		let id = obj.parentElement.getAttribute(\"id\");\r\n");
      out.write("		let num = Number(id.substring(id.length-1));\r\n");
      out.write("		console.log(id);\r\n");
      out.write("		\r\n");
      out.write("		let thumb = $(\"#upImgNameThumb\" + num).val();\r\n");
      out.write("		let origin = $(\"#upImgNameOrigin\" + num).val();\r\n");
      out.write("		\r\n");
      out.write("		console.log(thumb, origin);\r\n");
      out.write("		\r\n");
      out.write("		let url = '/missing/delImg';\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : url, // ajax와 통신 할 곳\r\n");
      out.write("			data : {origin : origin, thumb : thumb}, // 서블릿에 보낼 데이터\r\n");
      out.write("			dataType : \"text\", // 수신될 데이터의 타입\r\n");
      out.write("			type : \"POST\", // 통신 방식\r\n");
      out.write("			success : function(data) { // 통신 성공시 수행될 콜백 함수\r\n");
      out.write("				console.log(data);\r\n");
      out.write("				if (data == \"success\") {\r\n");
      out.write("					$(\"#\"+id).remove();\r\n");
      out.write("					if(num != \"3\") {\r\n");
      out.write("						for(let i=num; i<3; i++) {\r\n");
      out.write("							console.log(i+1);\r\n");
      out.write("							console.log($(\"#upImgNameThumb\"+(i+1)).val());\r\n");
      out.write("							$(\"#upImgNameThumb\" + i).val($(\"#upImgNameThumb\"+(i+1)).val());\r\n");
      out.write("							$(\"#upImgNameOrigin\" + i).val($(\"#upImgNameOrigin\"+(i+1)).val());\r\n");
      out.write("							$(\"#imgPreview\"+(i+1)).attr(\"id\", \"imgPreview\"+i);\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("					$(\"#upImgNameThumb3\").val(\"\");\r\n");
      out.write("					$(\"#upImgNameOrigin3\").val(\"\");\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function delUrlImg(obj) {\r\n");
      out.write("		let id = $(obj.parentElement).attr(\"id\");\r\n");
      out.write("		let num = Number(id.substring(id.length-1));\r\n");
      out.write("		\r\n");
      out.write("		$(obj.parentElement).remove();\r\n");
      out.write("		\r\n");
      out.write("		if(num != \"3\") {\r\n");
      out.write("			for(let i=num; i<3; i++) {\r\n");
      out.write("				$(\"#upImgNameOrigin\" + i).val($(\"#upImgNameOrigin\"+(i+1)).val());\r\n");
      out.write("				$(\"#imgPreview\"+(i+1)).attr(\"id\", \"imgPreview\"+i);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		$(\"#upImgNameThumb3\").val(\"\");\r\n");
      out.write("		$(\"#upImgNameOrigin3\").val(\"\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 이미지 파일이 아닌 파일이 있으면 true, 모두 이미지 파일이면 false\r\n");
      out.write("	function notImgCheck(uploadImgAr) {\r\n");
      out.write("		let extAr = [\"jpg\", \"png\", \"gif\", \"jpeg\"];\r\n");
      out.write("		let flag = false;\r\n");
      out.write("		for(let i=0; i<uploadImgAr.length; i++) {\r\n");
      out.write("			let ext = uploadImgAr[i].name.substring(uploadImgAr[i].name.lastIndexOf('.')+1);\r\n");
      out.write("			if(!extAr.includes(ext)) {\r\n");
      out.write("				flag = true;	\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		console.log(flag);\r\n");
      out.write("		return flag;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function showDropDiv() {\r\n");
      out.write("		$(\".fileContent\").show();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("	.fileContent {\r\n");
      out.write("		border : 1px dashed #3C6E9F;\r\n");
      out.write("		background-color:#ededed;\r\n");
      out.write("		border-radius: 4px;\r\n");
      out.write("		height : 150px;	\r\n");
      out.write("		display : none;	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	select {\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		padding: .5em .5em;\r\n");
      out.write("		border: 1px solid #999;\r\n");
      out.write("		font-family: inherit;\r\n");
      out.write("		background: url('../resources/images/missing/arrow.jpg') no-repeat 100% 50%;\r\n");
      out.write("		border-radius: 4px;\r\n");
      out.write("		-webkit-appearance: none;\r\n");
      out.write("		-moz-appearance: none;\r\n");
      out.write("		appearance: none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	select::-ms-expand {\r\n");
      out.write("	    display: none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.form-container {\r\n");
      out.write("		padding: 0 50px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.col-sm-offset-2 {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#phone_notice {\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("		color: #808080;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#phone_error {\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("		color: #ff7f00;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../template.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		  <h1>글 수정</h1>\r\n");
      out.write("		  <div class=\"form-container\">\r\n");
      out.write("			  <form class=\"form-horizontal\" action=\"/missing/update\" method=\"POST\">\r\n");
      out.write("			  	<input type=\"hidden\" name=\"no\" id=\"no\" />\r\n");
      out.write("			    <div class=\"form-group\">\r\n");
      out.write("			    	<label class=\"control-label col-sm-2\" for=\"title\">제목</label>\r\n");
      out.write("			      	<div class=\"col-sm-10\">\r\n");
      out.write("			        	<input type=\"text\" class=\"form-control\" id=\"title\" name=\"title\">\r\n");
      out.write("			      	</div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			    <div class=\"form-group\">\r\n");
      out.write("			      <label class=\"control-label col-sm-2\" for=\"writer\">작성자</label>\r\n");
      out.write("			      <div class=\"col-sm-10\">          \r\n");
      out.write("			        <input type=\"text\" class=\"form-control\" id=\"writer\" name=\"writer\" readonly>\r\n");
      out.write("			      </div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			    <fieldset>\r\n");
      out.write("			    	<legend style=\"color: #3C6E9F;\">동물 정보</legend>\r\n");
      out.write("				    <div class=\"form-group\">\r\n");
      out.write("				    	<label class=\"control-label col-sm-2\" for=\"animal\">동물</label>\r\n");
      out.write("				      	<div class=\"col-sm-2\">\r\n");
      out.write("				        	<select id=\"animal\" name=\"animal\">\r\n");
      out.write("				        		<option value=\"dog\">강아지</option>\r\n");
      out.write("				        		<option value=\"cat\">고양이</option>\r\n");
      out.write("				        		<option value=\"other\">다른 동물</option>\r\n");
      out.write("				        	</select>\r\n");
      out.write("				      	</div>\r\n");
      out.write("				      	<label class=\"control-label col-sm-2\" for=\"breed\">품종</label>\r\n");
      out.write("				      	<div class=\"col-sm-2\">\r\n");
      out.write("				        	<input type=\"text\" class=\"form-control\" id=\"breed\" name=\"breed\">\r\n");
      out.write("				     	</div>\r\n");
      out.write("				    	<label class=\"control-label col-sm-1\" for=\"gender\">성별</label>\r\n");
      out.write("				      	<div class=\"col-sm-3\">\r\n");
      out.write("				        	<select id=\"gender\" name=\"gender\">\r\n");
      out.write("				        		<option value=\"F\">암컷</option>\r\n");
      out.write("				        		<option value=\"M\">수컷</option>\r\n");
      out.write("				        		<option value=\"N\">성별모름</option>\r\n");
      out.write("				        	</select>\r\n");
      out.write("				      	</div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div class=\"form-group\">\r\n");
      out.write("				      	<label class=\"control-label col-sm-2\" for=\"name\">이름</label>\r\n");
      out.write("				      	<div class=\"col-sm-5\">          \r\n");
      out.write("				        	<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\">\r\n");
      out.write("				      	</div>\r\n");
      out.write("				      	<label class=\"control-label col-sm-2\" for=\"age\">나이</label>\r\n");
      out.write("				      	<div class=\"col-sm-3\">          \r\n");
      out.write("				        	 <select id=\"age\" name=\"age\">\r\n");
      out.write("				        		<option value=\"1살미만\">1살미만</option>\r\n");
      out.write("				        		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				        		<option value=\"30살이상\">30살이상</option>\r\n");
      out.write("				        	</select>\r\n");
      out.write("				      	</div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				\r\n");
      out.write("				    <div class=\"form-group\">\r\n");
      out.write("				   		<label class=\"control-label col-sm-2\" for=\"location\">실종 지역</label>\r\n");
      out.write("				      	<div class=\"col-sm-3\">          \r\n");
      out.write("				      		<select id=\"location\" name=\"location\">\r\n");
      out.write("				        		<option value=\"서울특별시\">서울특별시</option>\r\n");
      out.write("				        		<option value=\"경기도\">경기도</option>\r\n");
      out.write("				        		<option value=\"인천광역시\">인천광역시</option>\r\n");
      out.write("				        		<option value=\"강원도\">강원도</option>\r\n");
      out.write("				        		<option value=\"충청남도\">충청남도</option>\r\n");
      out.write("					        	<option value=\"대전광역시\">대전광역시</option>\r\n");
      out.write("				    	    	<option value=\"충청북도\">충청북도</option>\r\n");
      out.write("				        		<option value=\"세종특별자치시\">세종시</option>\r\n");
      out.write("				        		<option value=\"부산광역시\">부산광역시</option>\r\n");
      out.write("					        	<option value=\"울산광역시\">울산광역시</option>\r\n");
      out.write("				    	    	<option value=\"대구광역시\">대구광역시</option>\r\n");
      out.write("				        		<option value=\"경상북도\">경상북도</option>\r\n");
      out.write("				        		<option value=\"경상남도\">경상남도</option>\r\n");
      out.write("					        	<option value=\"전라남도\">전라남도</option>\r\n");
      out.write("				    	    	<option value=\"광주광역시\">광주광역시</option>\r\n");
      out.write("				        		<option value=\"전라북도\">전라북도</option>\r\n");
      out.write("				        		<option value=\"제주특별자치도\">제주도</option>\r\n");
      out.write("				        	</select>\r\n");
      out.write("				      	</div>\r\n");
      out.write("				      	<label class=\"control-label col-sm-2\" for=\"dlocation\">상세 장소</label>\r\n");
      out.write("				      	<div class=\"col-sm-5\">          \r\n");
      out.write("				        	<input type=\"text\" class=\"form-control\" id=\"dlocation\" name=\"dlocation\">\r\n");
      out.write("				      	</div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				        <div class=\"form-group\">\r\n");
      out.write("				      	<label class=\"control-label col-sm-2\" for=\"missingdate\">실종일자</label>\r\n");
      out.write("				      	<div class=\"col-sm-3\">          \r\n");
      out.write("				        	<input type=\"date\" class=\"form-control\" id=\"missingdate\" name=\"missingdate\">\r\n");
      out.write("				      	</div>\r\n");
      out.write("				      	<label class=\"control-label col-sm-2\" for=\"contact\">연락처</label>\r\n");
      out.write("				      	<div class=\"col-sm-5\">          \r\n");
      out.write("				        	<input type=\"text\" class=\"form-control\" id=\"contact\" name=\"contact\">\r\n");
      out.write("				        	<div id=\"phone_notice\">※ 010-0000-0000의 형식으로 입력해주세요</div>\r\n");
      out.write("				        	<div id=\"phone_error\"></div>\r\n");
      out.write("				      	</div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div class=\"form-group\">\r\n");
      out.write("				      	<label class=\"control-label col-sm-2\" for=\"contents\">특이사항</label>\r\n");
      out.write("				      	<div class=\"col-sm-10\">          \r\n");
      out.write("				        	<textarea class=\"form-control\" id=\"contents\" name=\"contents\" rows=\"15\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MissingBoard.contents }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("				      	</div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div class=\"form-group\">\r\n");
      out.write("				    	<label class=\"control-label col-sm-2\" for=\"contents\">사진</label>\r\n");
      out.write("				    	<div class=\"col-sm-10\">  \r\n");
      out.write("					    	<button type=\"button\" class=\"btn btn-default\" onclick=\"showDropDiv();\">파일 업로드</button>\r\n");
      out.write("							<div class=\"fileDrop\">\r\n");
      out.write("								<div class=\"fileContent\">\r\n");
      out.write("									<div>이 영역에 업로드 할 파일을 드래그 드롭 해주세요!</div>\r\n");
      out.write("									<div style=\"font-size:13px; color: gray;\">※첨부사진은 최대 3개까지 등록이 가능합니다.</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div id=\"uploadError\" style=\"color: red; font-weight: bold;\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"fDropList\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("				        <input type=\"hidden\" name=\"thumbimage\" id=\"upImgNameThumb1\" />\r\n");
      out.write("				        <input type=\"hidden\" name=\"image\" id=\"upImgNameOrigin1\" />\r\n");
      out.write("				        \r\n");
      out.write("				        <input type=\"hidden\" name=\"thumbimage\" id=\"upImgNameThumb2\" />\r\n");
      out.write("				        <input type=\"hidden\" name=\"image\" id=\"upImgNameOrigin2\" />\r\n");
      out.write("				        \r\n");
      out.write("				        <input type=\"hidden\" name=\"thumbimage\" id=\"upImgNameThumb3\" />\r\n");
      out.write("				        <input type=\"hidden\" name=\"image\" id=\"upImgNameOrigin3\" />\r\n");
      out.write("				    </div>\r\n");
      out.write("			    </fieldset>\r\n");
      out.write("			    <div class=\"form-group\">        \r\n");
      out.write("			      <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("			        <button type=\"submit\" class=\"btn btn-primary\">수정</button>\r\n");
      out.write("			        <button type=\"button\" class=\"btn btn-default\" id=\"cancelBtn\">취소</button>\r\n");
      out.write("			      </div>\r\n");
      out.write("			    </div>\r\n");
      out.write("		 </form>\r\n");
      out.write("		 </div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/missing/modifymissing.jsp(303,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /WEB-INF/views/missing/modifymissing.jsp(303,14) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(1);
      // /WEB-INF/views/missing/modifymissing.jsp(303,14) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(29);
      // /WEB-INF/views/missing/modifymissing.jsp(303,14) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setStep(1);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				        			<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('살');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("살</option>\r\n");
            out.write("				        		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
